// デフォルト12ボタン設定
export const DEFAULT_FILTER_BUTTONS = [
  // Row 1: 未読フィルター
  {
    id: 'filter-0',
    type: 'unread',
    label: '未読',
    emoji: '📩',
    roomIds: [],
    active: false,
    editable: false,
  },
  {
    id: 'filter-1',
    type: 'unread',
    label: 'TO',
    emoji: '🔔',
    roomIds: [],
    active: false,
    editable: false,
  },
  {
    id: 'filter-2',
    type: 'unread',
    label: '新着',
    emoji: '🆕',
    roomIds: [],
    active: false,
    editable: false,
  },
  // Row 2: ブックマーク
  {
    id: 'filter-3',
    type: 'bookmark',
    label: 'ブクマ1',
    emoji: '⭐',
    roomIds: [],
    active: false,
    editable: true,
  },
  {
    id: 'filter-4',
    type: 'bookmark',
    label: 'ブクマ2',
    emoji: '📌',
    roomIds: [],
    active: false,
    editable: true,
  },
  {
    id: 'filter-5',
    type: 'bookmark',
    label: 'ブクマ3',
    emoji: '🔖',
    roomIds: [],
    active: false,
    editable: true,
  },
  // Row 3: 保存1
  {
    id: 'filter-6',
    type: 'save',
    label: '保存1',
    emoji: '📁',
    roomIds: [],
    active: false,
    editable: true,
  },
  {
    id: 'filter-7',
    type: 'save',
    label: '保存2',
    emoji: '📂',
    roomIds: [],
    active: false,
    editable: true,
  },
  {
    id: 'filter-8',
    type: 'save',
    label: '保存3',
    emoji: '💼',
    roomIds: [],
    active: false,
    editable: true,
  },
  // Row 4: 保存2
  {
    id: 'filter-9',
    type: 'save',
    label: '保存4',
    emoji: '🏷️',
    roomIds: [],
    active: false,
    editable: true,
  },
  {
    id: 'filter-10',
    type: 'save',
    label: '保存5',
    emoji: '📋',
    roomIds: [],
    active: false,
    editable: true,
  },
  {
    id: 'filter-11',
    type: 'save',
    label: '保存6',
    emoji: '🗂️',
    roomIds: [],
    active: false,
    editable: true,
  },
];

// 絵文字リスト（カテゴリ別）
export const EMOJI_LIST = {
  よく使う: [
    '⭐',
    '📌',
    '🔖',
    '📁',
    '📂',
    '💼',
    '🏷️',
    '📋',
    '🗂️',
    '📩',
    '🔔',
    '🆕',
    '✅',
    '❌',
    '❗',
    '❓',
    '💬',
    '📝',
    '🔍',
    '💡',
  ],
  表情: [
    '😀',
    '😊',
    '😎',
    '🤔',
    '😍',
    '🥳',
    '😴',
    '🤗',
    '😱',
    '🥺',
    '😤',
    '🤓',
    '😈',
    '👻',
    '💀',
    '🤖',
    '👽',
    '😺',
    '🙈',
    '💩',
  ],
  動物: [
    '🐶',
    '🐱',
    '🐭',
    '🐹',
    '🐰',
    '🦊',
    '🐻',
    '🐼',
    '🐨',
    '🐯',
    '🦁',
    '🐮',
    '🐷',
    '🐸',
    '🐵',
    '🐔',
    '🐧',
    '🐦',
    '🦅',
    '🦆',
  ],
  食べ物: [
    '🍎',
    '🍊',
    '🍋',
    '🍇',
    '🍓',
    '🍑',
    '🍒',
    '🥑',
    '🍕',
    '🍔',
    '🍟',
    '🌮',
    '🍣',
    '🍜',
    '🍩',
    '🍪',
    '🎂',
    '🍫',
    '☕',
    '🍺',
  ],
  オブジェクト: [
    '📱',
    '💻',
    '⌨️',
    '🖥️',
    '📷',
    '📹',
    '🎵',
    '🎮',
    '🔧',
    '🔨',
    '💎',
    '🔑',
    '📦',
    '🎁',
    '🏠',
    '🚀',
    '⚡',
    '🔥',
    '💧',
    '🌈',
  ],
  記号: [
    '❤️',
    '🧡',
    '💛',
    '💚',
    '💙',
    '💜',
    '🖤',
    '🤍',
    '♠️',
    '♣️',
    '♥️',
    '♦️',
    '🔴',
    '🟠',
    '🟡',
    '🟢',
    '🔵',
    '🟣',
    '⚫',
    '⚪',
  ],
};

// フィルターグリッドの固定高さ (px)
export const FILTER_GRID_HEIGHT = 190;

// Chatworkのセレクタ候補（フォールバック用に複数）
export const SELECTORS = {
  sidebarSwitch: ['#sidebarSwitch', '[data-testid="sidebar-switch"]'],
  sidebarPane: ['#_sidebarPane', '[data-testid="sidebar-pane"]'],
  roomListContainer: [
    '#_roomListContainer',
    '#RoomList',
    '[data-testid="room-list-container"]',
    '.sc-room-list',
  ],
  roomItem: [
    '[role="listitem"]',
    'li[data-rid]',
    '.roomListItem',
    '.chakra-stack > div[data-rid]',
    '[data-testid="room-list-item"]',
  ],
  roomId: ['data-rid', 'data-room-id'],
  unreadBadge: ['.unreadBadge', '[data-unread]', '.badge--unread', '.sc-dnqmqq', '.chakra-badge'],
  mentionBadge: ['.mentionBadge', '[data-mention]', '.badge--mention', '.toMeBadge'],
};

// CSSクラス定数
export const CSS_CLASSES = {
  grid: 'cw-filter-grid',
  tile: 'cw-filter-tile',
  tileActive: 'cw-filter-tile--active',
  tileEditing: 'cw-filter-tile--editing',
  tileEmoji: 'cw-filter-tile__emoji',
  tileLabel: 'cw-filter-tile__label',
  tileBadge: 'cw-filter-tile__badge',
  tileInput: 'cw-filter-tile__input',
  emojiPicker: 'cw-emoji-picker',
  emojiPickerTabs: 'cw-emoji-picker__tabs',
  emojiPickerTab: 'cw-emoji-picker__tab',
  emojiPickerTabActive: 'cw-emoji-picker__tab--active',
  emojiPickerGrid: 'cw-emoji-picker__grid',
  emojiPickerItem: 'cw-emoji-picker__item',
  roomAddBtn: 'cw-room-add-btn',
  roomAddBtnActive: 'cw-room-add-btn--active',
};
